"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Camera, Search, Square } from "lucide-react";
import { PageIntro } from "@/components/shared/PageIntro";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAppData } from "@/context/AppDataContext";

type Detector = { detect: (source: HTMLVideoElement) => Promise<Array<{ rawValue: string }>> };
type DetectorConstructor = new (options: { formats: string[] }) => Detector;

export default function ScannerPage() {
  const data = useAppData(); const router = useRouter();
  const [code, setCode] = useState(""); const [error, setError] = useState(""); const [scanning, setScanning] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const frameRef = useRef<number | null>(null);
  function openCustomer(value: string) { const normalized = value.trim(); const customer = data.customers.find((item) => item.qrCode.toLowerCase() === normalized.toLowerCase() || item.id === normalized); if (!customer) { setError("No customer matches this QR code."); return; } stopCamera(); router.push(`/dashboard/customers/${customer.id}`); }
  function stopCamera() { if (frameRef.current) cancelAnimationFrame(frameRef.current); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setScanning(false); }
  async function startCamera() { setError(""); const BarcodeDetector = (window as unknown as { BarcodeDetector?: DetectorConstructor }).BarcodeDetector; if (!BarcodeDetector) { setError("Camera scanning is not supported in this browser. Enter the QR code below."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } const detector = new BarcodeDetector({ formats: ["qr_code"] }); setScanning(true); const scan = async () => { if (!videoRef.current || !streamRef.current) return; try { const codes = await detector.detect(videoRef.current); if (codes[0]?.rawValue) { openCustomer(codes[0].rawValue); return; } } catch { /* retry next frame */ } frameRef.current = requestAnimationFrame(scan); }; frameRef.current = requestAnimationFrame(scan); } catch { setError("Camera permission was denied. Enter the QR code below."); } }
  useEffect(() => () => { streamRef.current?.getTracks().forEach((track) => track.stop()); if (frameRef.current) cancelAnimationFrame(frameRef.current); }, []);
  return <div className="mx-auto max-w-3xl space-y-6"><PageIntro eyebrow="Staff scanner" title="Scan a customer at the counter." description="Open their profile, record the visit, and add points in seconds." /><Card className="glass-card border-0 ring-0"><CardHeader><CardTitle className="card-title">QR scanner</CardTitle></CardHeader><CardContent><div className="relative grid aspect-video max-h-[420px] place-items-center overflow-hidden rounded-2xl border border-line bg-surface-soft"><video ref={videoRef} className={`h-full w-full object-cover ${scanning ? "block" : "hidden"}`} muted playsInline />{!scanning ? <div className="text-center"><Camera className="mx-auto h-10 w-10 text-faint" /><p className="mt-3 text-sm font-bold text-ink">Ready to scan</p><p className="mt-1 text-xs text-muted">Use the rear camera for the best result.</p></div> : <div className="pointer-events-none absolute inset-[18%] rounded-2xl border-2 border-white shadow-[0_0_0_999px_#0005]" />}</div><div className="mt-4 flex justify-center">{scanning ? <Button variant="outline" onClick={stopCamera} className="gap-2"><Square className="h-4 w-4" /> Stop camera</Button> : <Button onClick={startCamera} className="gap-2 bg-purple text-white"><Camera className="h-4 w-4" /> Start camera</Button>}</div><div className="my-6 flex items-center gap-3 text-[10px] uppercase tracking-widest text-faint"><span className="h-px flex-1 bg-line" />or enter a code<span className="h-px flex-1 bg-line" /></div><form onSubmit={(event) => { event.preventDefault(); openCustomer(code); }} className="flex gap-2"><Input value={code} onChange={(event) => { setCode(event.target.value); setError(""); }} placeholder="PK-MAYA-KIM" className="h-10" /><Button type="submit" className="gap-2"><Search className="h-4 w-4" /> Find</Button></form>{error ? <p role="alert" className="mt-3 rounded-lg bg-destructive/10 p-3 text-xs font-semibold text-destructive">{error}</p> : null}</CardContent></Card><Card className="glass-card border-0 ring-0"><CardHeader><CardTitle className="card-title">Try a customer</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{data.customers.slice(0, 5).map((customer) => <Button key={customer.id} variant="outline" size="sm" onClick={() => openCustomer(customer.qrCode)}>{customer.name}</Button>)}</CardContent></Card></div>;
}
